export * as confirm from './confirm/confirm';
export * as file from './file/file';
export * as loading from './loading/loading';
export * as message from './message/message';
export * as native from './native/native';
export * as otp from './otp/otp';
export * as payment from './payment/payment';
export * as pichak from './pichak/pichak';
export * as qrCode from './qr-code/qr-code';
